/** Fields that typically live on Stmt/attachment pages with poor OCR — scored separately. */
export const TAX_ATTACHMENT_FIELD_IDS = new Set([
  "bank_credit_card",
  "professional_fees",
  "utilities",
  "other_operating_expenses",
  "amortization",
]);

export type WorkbookComparisonFixture = {
  benchmark: Record<
    string,
    {
      currentRatio: number;
      quickRatio: number;
      returnOnEquity: number;
      returnOnAssets: number;
    }
  >;
  tax: Record<
    string,
    {
      year: number;
      values: Record<string, number>;
      top8Amounts?: number[];
      top8Labels?: string[];
    }
  >;
};

export const WORKBOOK_COMPARISON_FIXTURES: WorkbookComparisonFixture = {
  benchmark: {
    "MAIN CURRENT EXCEL.xlsx": {
      currentRatio: 3.5,
      quickRatio: 1.76,
      returnOnEquity: 0.3039,
      returnOnAssets: 0.0962,
    },
    "KCF MAIN CURRENT EXCEL.xlsx": {
      currentRatio: 4.55,
      quickRatio: 3.11,
      returnOnEquity: 0.4425,
      returnOnAssets: 0.2208,
    },
  },
  tax: {
    "KCF MAIN CURRENT EXCEL.xlsx / 2025": {
      year: 2025,
      top8Labels: [
        "Officer compensation",
        "Salaries and wages",
        "Advertising",
        "Rent",
        "Taxes and Licenses",
        "Bank and credit card",
        "Professional fees",
        "Utilities",
      ],
      top8Amounts: [91000, 193583, 19341, 125016, 27275, 28041, 31897, 7584],
      values: {
        sales: 1027658,
        cogs: 329674,
        depreciation: 12860,
        amortization: 0,
        officer_compensation: 91000,
        salaries_wages: 193583,
        advertising: 19341,
        rent: 125016,
        taxes_licenses: 27275,
        bank_credit_card: 28041,
        professional_fees: 31897,
        utilities: 7584,
        other_operating_income: 0,
        other_operating_expenses: 27110,
        interest_expense: 12097,
        other_income: 3259,
        other_expenses: 0,
        adjusted_owner_compensation: 0,
        taxes_paid: 0,
        extraordinary_gain: 0,
        extraordinary_loss: 0,
        cash: 247928,
        accounts_receivable: 0,
        inventory: 5000,
        other_current_assets: 14203,
        gross_fixed_assets: 187910,
        accumulated_depreciation: 187910,
        gross_intangible_assets: 283400,
        accumulated_amortization: 283400,
        other_assets: 11000,
        accounts_payable: 0,
        short_term_debt: 0,
        current_portion_ltd: 0,
        other_current_liabilities: 49749,
        notes_minus_short_term: 61800,
        subordinated: 0,
        other_long_term_liabilities: 0,
        preferred_stock: 0,
        common_stock: 0,
        additional_paid_in_capital: 0,
        other_stock_equity: 0,
        unclassified_equity: 166582,
      },
    },
    "KCF MAIN CURRENT EXCEL.xlsx / 2024": {
      year: 2024,
      top8Labels: [
        "Officer compensation",
        "Salaries and wages",
        "Advertising",
        "Rent",
        "Taxes and Licenses",
        "Bank and credit card",
        "Professional fees",
        "Utilities",
      ],
      top8Amounts: [87000, 182187, 19737, 122219, 26919, 32099, 35513, 8749],
      values: {
        sales: 1066455,
        cogs: 313334,
        depreciation: 0,
        amortization: 0,
        officer_compensation: 87000,
        salaries_wages: 182187,
        advertising: 19737,
        rent: 122219,
        taxes_licenses: 26919,
        bank_credit_card: 32099,
        professional_fees: 35513,
        utilities: 8749,
        other_operating_income: 0,
        other_operating_expenses: 17891,
        interest_expense: 14533,
        other_income: 0,
        other_expenses: 0,
        adjusted_owner_compensation: 0,
        taxes_paid: 0,
        extraordinary_gain: 0,
        extraordinary_loss: 0,
        cash: 280309,
        accounts_receivable: 0,
        inventory: 5000,
        other_current_assets: 0,
        gross_fixed_assets: 175050,
        accumulated_depreciation: 175050,
        gross_intangible_assets: 283400,
        accumulated_amortization: 283400,
        other_assets: 11000,
        accounts_payable: 0,
        short_term_debt: 0,
        current_portion_ltd: 0,
        other_current_liabilities: 52003,
        notes_minus_short_term: 60875,
        subordinated: 0,
        other_long_term_liabilities: 0,
        preferred_stock: 0,
        common_stock: 0,
        additional_paid_in_capital: 0,
        other_stock_equity: 0,
        unclassified_equity: 183431,
      },
    },
    "KCF MAIN CURRENT EXCEL.xlsx / 2023": {
      year: 2023,
      top8Labels: [
        "Officer compensation",
        "Salaries and wages",
        "Advertising",
        "Rent",
        "Taxes and Licenses",
        "Bank and credit card",
        "Professional fees",
        "Utilities",
      ],
      top8Amounts: [65000, 178811, 19882, 146427, 28773, 66722, 33200, 7787],
      values: {
        sales: 1086475,
        cogs: 372306,
        depreciation: 0,
        amortization: 14174,
        officer_compensation: 65000,
        salaries_wages: 178811,
        advertising: 19882,
        rent: 146427,
        taxes_licenses: 28773,
        bank_credit_card: 66722,
        professional_fees: 33200,
        utilities: 7787,
        other_operating_income: 0,
        other_operating_expenses: 17425,
        interest_expense: 17187,
        other_income: 0,
        other_expenses: 0,
        adjusted_owner_compensation: 0,
        taxes_paid: 0,
        extraordinary_gain: 0,
        extraordinary_loss: 0,
        cash: 221806,
        accounts_receivable: 0,
        inventory: 5000,
        other_current_assets: 0,
        gross_fixed_assets: 175050,
        accumulated_depreciation: 175050,
        gross_intangible_assets: 283400,
        accumulated_amortization: 283400,
        other_assets: 0,
        accounts_payable: 0,
        short_term_debt: 0,
        current_portion_ltd: 0,
        other_current_liabilities: 54043,
        notes_minus_short_term: 68139,
        subordinated: 0,
        other_long_term_liabilities: 0,
        preferred_stock: 0,
        common_stock: 0,
        additional_paid_in_capital: 0,
        other_stock_equity: 0,
        unclassified_equity: 104624,
      },
    },
  },
};